### ISSUE TITLE
Jcenter shutdown - build is failing due to the okhttp-digest

### ISSUE THREAD

**Issue by tmantis01** [dwclark/http-builder-ng#232]
Hello,

I removed the **Jcenter** from my project because it will shutdown (https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)
but the build is failing because it can't find the: 
"com.burgstaller:okhttp-digest:1.10"

The okhttp-digest has been moved to maven 10 days ago in "**io.github.rburgst:okhttp-digest:2.5**"(https://github.com/rburgst/okhttp-digest/issues/71)

Is it possible to use the new which is in maven central?

**Comment by cjstehno** [comment]
This project has gone dormant (see #230).
