### ISSUE TITLE
JavaDocs For Main API classes.

### ISSUE THREAD

**Issue by dwclark** [dwclark/http-builder-ng#3]
JavaDocs need to be written for main API entry points which are:

https://github.com/dwclark/http-builder-ng/blob/master/src/main/java/groovyx/net/http/ChainedHttpConfig.java

https://github.com/dwclark/http-builder-ng/blob/master/src/main/java/groovyx/net/http/FromServer.java

https://github.com/dwclark/http-builder-ng/blob/master/src/main/java/groovyx/net/http/HttpBuilder.java

https://github.com/dwclark/http-builder-ng/blob/master/src/main/java/groovyx/net/http/HttpConfig.java

https://github.com/dwclark/http-builder-ng/blob/master/src/main/java/groovyx/net/http/HttpObjectConfig.java

https://github.com/dwclark/http-builder-ng/blob/master/src/main/java/groovyx/net/http/ToServer.java

Other classes are mostly interesting to people writing extensions, not for people who are just using the library. Javadocs for those would be nice, but not necessary.

**Comment by cjstehno** [comment]
I am going to call this "done"... there are still some classes that could use more documentation, but I will add them as I come across them. The main/common stuff is documented.
