### ISSUE TITLE
JavaHttpBuilder writes quoted cookie values 

### ISSUE THREAD

**Issue by cjstehno** [dwclark/http-builder-ng#7]
The `JavaHttpBuilder` is writing cookie values incorrectly (with quotes). I double-checked to make sure it was not my mock server testing causing the issue, but it verifies against a simple request dumper:

```
Apache
[nio-8080-exec-1] com.example.DemoApplication: Requested Uri: /foo
[nio-8080-exec-1] com.example.DemoApplication: Cookie[biscuit]: wafer

Java
[nio-8080-exec-2] com.example.DemoApplication: Requested Uri: /foo
[nio-8080-exec-2] com.example.DemoApplication: Cookie[biscuit]: "wafer"
```
Notice the quoted cookie value in the Java version - this should not be quoted. There is an ignored test in `HttpGetSpec` (on `cjs-documentation` branch) with a test of this issue. It passes for the Apache builder but fails for the Java builder.

**Comment by dwclark** [comment]
I'm wondering if this is due to a difference in versions. Apache Http client may set a different cookie level by default than the native Java implementation. See setVersion of https://docs.oracle.com/javase/7/docs/api/index.html?java/net/HttpCookie.html

**Comment by cjstehno** [comment]
It's the version issue. Java client is set to version 1, Apache is set to 1, and servlet API expects 0 by default. I will have a fix in my branch making it default to 0 with the ability to configure it if needed.
